// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHuTaZ-UOpp7PMuBX5MSlaLgQ49FEciI0',
    appId: '1:1080040738434:web:c88c13c441a46a2d12ee9b',
    messagingSenderId: '1080040738434',
    projectId: 'bnas-bbf21',
    authDomain: 'bnas-bbf21.firebaseapp.com',
    storageBucket: 'bnas-bbf21.appspot.com',
    measurementId: 'G-YRW2V310QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ev8EVujzWCVlsppqCCvKgUcNp893I7A',
    appId: '1:1080040738434:android:5e663c4435313cbe12ee9b',
    messagingSenderId: '1080040738434',
    projectId: 'bnas-bbf21',
    storageBucket: 'bnas-bbf21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOpHogP_zBe4aNz4GbnVzWIII5g25s5bA',
    appId: '1:1080040738434:ios:912bc90e56d2167412ee9b',
    messagingSenderId: '1080040738434',
    projectId: 'bnas-bbf21',
    storageBucket: 'bnas-bbf21.appspot.com',
    iosBundleId: 'io.webflow.nobsfrica.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOpHogP_zBe4aNz4GbnVzWIII5g25s5bA',
    appId: '1:1080040738434:ios:6bfda200568dadb712ee9b',
    messagingSenderId: '1080040738434',
    projectId: 'bnas-bbf21',
    storageBucket: 'bnas-bbf21.appspot.com',
    iosBundleId: 'io.webflow.nobsfrica.mynotes.RunnerTests',
  );
}
